server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: business-microservice01-product
          uri: lb://business-microservice01-product
          predicates:
            - Path=/api/products/**
        - id: business-microservice02-customer
          uri: lb://business-microservice02-customer
          predicates:
            - Path=/api/customers/**
        - id: business-microservice03-operation
          uri: lb://business-microservice03-operation
          predicates:
            - Path=/api/passiveoperations/**
        - id: business-microservice04-location
          uri: lb://business-microservice04-location
          predicates:
            - Path=/api/locations/**
        - id: business-microservice04-reports
          uri: lb://business-microservice04-reports
          predicates:
            - Path=/api/reports/**  
        - id: business-microservice06-coinbank
          uri: lb://business-microservice06-coinbank
          predicates:
            - Path=/api/reports/**  